Dockerfile: switch to existing working python-numpy-pandas base image
Build fails on dockerhub with:

    Running setup.py bdist_wheel for cchardet:
    [...]
    error: command 'gcc' failed with exit status 1